name: Naqsh Rust CI

on:
  push:
    paths:
      - naqsh-rs
      - .github/workflows/naqsh-rs-ci.yml
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -p naqsh --verbose
    - name: Run tests
      run: cargo test -p naqsh --verbose
